---

- name: Restart MongoDB
  service: name=mongod state=restarted enabled=yes
  when: mrcrilly_mongodb_manage_service | default(true)

- name: Start MongoDB
  service: name=mongod state=started enabled=yes
  when: mrcrilly_mongodb_manage_service | default(true)
